# .sqa/config.yml - jenkins-pipeline-library configuration file
environment:
  JPL_DOCKERFORCEBUILD: "True"
  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      ai4os-fasterrcnn-torch:
        container: thisrepo-testing
        commands:
        - sh -c 'git submodule update --init --remote --recursive'
        - tox -e qc.sty
  qc_coverage:
    repos:
      ai4os-fasterrcnn-torch:
        container: thisrepo-testing
        commands:
        - sh -c 'git submodule update --init --remote --recursive'
        - tox -e qc.cov
  qc_security:
    repos:
      ai4os-fasterrcnn-torch:
        container: thisrepo-testing
        commands:
        - sh -c 'git submodule update --init --remote --recursive'
        - tox -e qc.cov

timeout: 600
