FROM ai4oshub/ci-images:python3.10
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgl1 \
        libglib2.0-0 \
        unzip && \
    rm -rf /var/lib/apt/lists/*