version: "3.6"

services:
  thisrepo-testing:
    container_name: "${BUILD_TAG}"
    hostname: "${BUILD_TAG}"
    working_dir: /srv
    build:
      context: ./.sqa
      dockerfile: Dockerfile.cicd
    command: >
      sh -c "git config --global --add safe.directory /srv &&
             git config --global --add safe.directory /srv/fasterrcnn_pytorch_training_pipeline &&
             tail -f /dev/null"
    volumes:
      - type: bind
        source: ./
        target: /srv
